global:
  sendAnonymousUsage: false
api:
  insecure: false
  dashboard: true
  debug: false
providers:
  docker:
    exposedbydefault: false  
  file:
    filename: /etc/traefik/dynamic_config.yml
    watch: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
log:
  level: debug

